Feat/auth
codeNamesLEMFA01/backend pull request #11
Opened 2024-09-01 18:31 UTC by Eolran

2024-09-02 08:28 UTC, Corentin-kzk requested changes

2024-09-02 08:28 UTC, Corentin-kzk commented on app/auth/authServices.py
> +# async def get_current_active_user(
comment ??

2024-09-02 08:28 UTC, Corentin-kzk commented on app/auth/seedDb.py
> +    ]
a dépacer dans data et a nommé User.mock.py

2024-09-02 08:28 UTC, Corentin-kzk commented on app/auth/seedDb.py
> +            logging.error(f"Error inserting users to db: {str(e)}")
pas besoins de batch pour du json insert-many fonctionne pour si peu de data

2024-09-02 08:28 UTC, Corentin-kzk commented on app/cron/seedDb.py
> +            # seed_users_db()
pourquoi comment le seed de la db ?

2024-09-02 08:28 UTC, Corentin-kzk commented on app/cron/seedDb.py
> +            # return result
??

2024-09-02 08:28 UTC, Corentin-kzk commented on app/cron/seedDb.py
> +            # seed_users_db()
doit etre appelé dans cron.py

2024-09-02 08:28 UTC, Corentin-kzk commented on app/main.py
> +# from .routers.posts import router as posts_router
comment

2024-09-02 08:28 UTC, Corentin-kzk commented on app/main.py
> +    main()
a retirer et mettre a jour par rapport a dev

2024-09-02 08:28 UTC, Corentin-kzk commented on app/models/token.py
> +from pydantic import BaseModel
pourquoi pydantic ?? il n'est pas présent sur le projet on utilise mongoengine

2024-09-02 08:28 UTC, Corentin-kzk commented on app/models/token.py
> +    username: str | None = None
a passer sur mongo engine

2024-09-02 08:28 UTC, Corentin-kzk commented on app/models/users.py
> +from pydantic import BaseModel
pourquoi pydantic ?? il n'est pas présent sur le projet on utilise mongoengine

2024-09-02 08:28 UTC, Corentin-kzk commented on app/models/users.py
> +from pydantic import BaseModel
et non utilisé

2024-09-02 08:28 UTC, Corentin-kzk commented on app/routers/auth.py
> +# Tried from here : https://fastapi.tiangolo.com/tutorial/security/
comment ?

2024-09-02 08:28 UTC, Corentin-kzk commented on app/routers/auth.py
> +ACCESS_TOKEN_EXPIRE_MINUTES = 30
peut etre passé en .env ??

2024-09-02 08:28 UTC, Corentin-kzk commented on app/routers/auth.py
> +    form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
pourquoi Depends() ?? cela ne sert-il pas a rien vue que aucune dependence n'est appelé dans le depend

2024-09-02 08:28 UTC, Corentin-kzk commented on app/routers/auth.py
> +#     return current_user
comment ??

2024-09-02 09:23 UTC, Eolran commented on app/routers/auth.py
> +#     return current_user
J'ai pas réussi a le fix et je voulais pas bloquer Fred trop longtemps. J'ai des soucis pour récupérer le "disabled".

2024-09-02 09:24 UTC, Eolran commented on app/cron/seedDb.py
> +            # return result
Dans l'ancienne version, malgré la condition le seed se faisait quand même. Pour pas attendre 20min d'erreurs a chaque hot reload j'ai seed une fois ma db puis je l'ai commenté. Rien de grave.

2024-09-02 09:25 UTC, Eolran commented on app/cron/seedDb.py
> +            # seed_users_db()
Dans l'ancienne version, malgré la condition le seed se faisait quand même. Pour pas attendre 20min d'erreurs a chaque hot reload j'ai seed une fois ma db puis je l'ai commenté. Rien de grave.

2024-09-02 09:25 UTC, Eolran commented on app/main.py
> +# from .routers.posts import router as posts_router
A modifier. Erreur de rebase.

2024-09-02 11:40 UTC, kohai-fred commented on app/routers/auth.py
> +#     return current_user
pour le login il me faudra aussi la route /me

2024-09-02 11:53 UTC, Eolran commented on app/routers/auth.py
> +#     return current_user
C'est en cours de debug, je voulais que tu puisse en prio accéder au /login

2024-09-03 09:53 UTC, Eolran commented on app/routers/auth.py
> +    form_data: Annotated[OAuth2PasswordRequestForm, Depends()],
La classe Annotated[] force l'argument Depends, si elle est vide, la route est libre, sinon elle est protégée.

2024-09-04 12:42 UTC, Corentin-kzk approved these changes

2024-09-04 12:44 UTC, merged